import type { StrikeDipMeasurement } from "./strike-dip-measurements.ts";

/** Recover only the exact label format generated by older compass captures. */
export function normalizeLineationRecord<T extends StrikeDipMeasurement>(record: T): T {
  const match = /^Lineation\s+(\d{1,3}(?:\.\d+)?)°\s*\/\s*(\d{1,2}(?:\.\d+)?)°$/.exec(record.label?.trim() ?? "");
  const azimuth = match ? Number(match[1]) : undefined;
  const plunge = match ? Number(match[2]) : undefined;
  const generated = azimuth !== undefined && azimuth >= 0 && azimuth < 360 && plunge !== undefined && plunge >= 0 && plunge <= 90;
  const noPlaneValues = !record.strike?.trim() && !record.dip?.trim();
  const lineation = record.measurementType === "lineation" || (noPlaneValues && (generated || record.featureType === "Lineation" || (Number.isFinite(record.trendDegrees) && Number.isFinite(record.plungeDegrees))));
  if (!lineation) return record;
  const next = { ...record, measurementType: "lineation" as const,
    trendDegrees: record.trendDegrees ?? (generated ? azimuth : undefined),
    plungeDegrees: record.plungeDegrees ?? (generated ? plunge : undefined),
    label: generated ? "Lineation" : record.label,
  };
  return JSON.stringify(next) === JSON.stringify(record) ? record : next;
}
